=begin
#reattract.io API v1

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1
Contact: support@reattract.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

module OpenapiClient
  VERSION = '1.0.0'
end
