/**
 * reattract.io API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * Contact: support@reattract.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserAuthenticationUser } from '../models/UserAuthenticationUser';
import { HttpFile } from '../http/http';

export class UserAuthentication {
    'user': UserAuthenticationUser;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "UserAuthenticationUser",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserAuthentication.attributeTypeMap;
    }

    public constructor() {
    }
}

