# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in reattract.gemspec
gemspec

gem 'guard', '~> 2.18'
gem 'guard-rspec', '~> 4.7'
gem 'guard-rubocop', '~> 1.5'

gem 'rake', '~> 13.0'
gem 'rspec', '~> 3.0'
gem 'rubocop', '~> 1.46'
gem 'rubocop-performance', '~> 1.16'
gem 'rubocop-rake', '~> 0.6.0'
gem 'rubocop-rspec', '~> 2.18'
